### ISSUE TITLE
w3w order meta data does not appear to being saved on checkout

### ISSUE THREAD

**Issue by willfaulds** [what3words/wordpress-autosuggest-plugin#17]
I've combed through the code a reasonable amount but Github's search facility seems to mis-behaving tonight - HOWEVER I can't find anywhere in the plugin a call to tell WooCommerce/Wordpress to save the w3w plugin's form input's/post data after checkout to the order's meta.

I'm not familiar enough to know if this is perhaps a new-ish behavior of WooCommerce/Wordpress but can confirm after multiple tests that the meta data is not being saved.

Woo 5.5.2
WP 5.8
w3w plugin Version 4.0.0

I have tried disabling plugins etc. to be sure of no conflicts.

Overview of an UNTESTED solution -

```php
function save_w3w_checkout_data_in_order_metadata( $order_id, $data ) {

	$w3w_keys = [
		'billing_w3w_lng',
		'billing_w3w_lat',
		'billing_w3w',
//this is not an exhaustive list
	];

	$order = wc_get_order( $order_id );

	foreach ( $w3w_keys as $key ) {
		if ( isset( $data[ $key ] ) ) {
//maybe sanitise?
			$order->add_meta_data( $key, $data[ $key ] );
		}
	}

	$order->save();
}
add_action( 'woocommerce_checkout_update_order_meta', save_w3w_checkout_data_in_order_metadata);
```

**Comment by c5haw** [comment]
Hi @willfaulds,

I'm not sure I understand the nature of your problem, but if it helps I'm happy to clarify how the what3words fields are added to the order, saved against the order and where you can find them in the WordPress database.

The solution we have opted for is rather than hooking into the action you mentioned `woocommerce_checkout_update_order_meta` action we have opted for the [following filter](https://github.com/what3words/wordpress-autosuggest-plugin/blob/master/w3w-autosuggest/public/class-w3w-autosuggest-public.php#L192) which is triggered by 

```
add_filter( 'woocommerce_checkout_fields', 'add_fields_to_checkout_form' );
```

This adds the the fields to the checkout form and the WooCommerce plugin handles storing this data against the order in the same manner in which it does for other fields in the form.

The Order is subsequently stored in the DB in `wp_posts` table and the field data is in the `wp_postmeta` table along with all the other data associated with the order.

**Comment by willfaulds** [comment]
Thanks for such a prompt reply @c5haw , I am doing some testing today and will verify against a clean WP & WooC install.

The problem I encountered was that the w3w order meta was not saved to the DB but will verify again and come back to you.

**Comment by willfaulds** [comment]
@c5haw 

I can confirm on a completely clean install that the w3w plugin does not display captured w3w field's data in the admin area nor do I believe it is storing the captured w3w field's data.

I'm no expert but believe the data should be being stored in `woocommerce_order_itemmeta` rather than `wp_postmeta` however WP/WooC handle this so its unimportant.

I've checked whether the meta data is stored via "Order Meta Editor for Woocommerce" plugin and manually using phpMyAdmin and cannot find any w3w data being stored.

My w3w plugin settings should be storing the w3w address field, lat, and lng coordinates but these are not stored.

**Comment by willfaulds** [comment]
OK, so I think I've finally worked out what's going on... I can't find any call in the w3w plugin to add the w3w field data to the WooC order view? So there is currently no way of viewing this info without digging into the `wp_postmeta ` table?

**Comment by willfaulds** [comment]
Aha!!!

I *think* I solved it...

https://github.com/what3words/wordpress-autosuggest-plugin/blob/104506356bcd34932cc8c83935c7d9f71781c362/w3w-autosuggest/admin/class-w3w-autosuggest-admin.php#L195

only renders if `_shipping_w3w` but by default WooC stores the data in `_billing_w3w`

**Comment by willfaulds** [comment]
Yes!

I was using default clean install setups which I had not fulling setup WooCommerce shipping zones. That indeed caused the issue.

Thank you for your patience and prompt replies

**Comment by c5haw** [comment]
@willfaulds - no problem. Thanks for letting us know of your issue and I'm glad we were able to get it resolved. Will close this issue now. Thanks
